aai-signal-transmission: "信号传输"
aai-storehouse-base: "库房"
aai-storehouse-logistic: "物流库"
aai-storehouse-storage: "存货库"
aai-strongbox-base: "柜子"
aai-strongbox-logistic: "物流柜"
aai-strongbox-storage: "存货柜"
aai-warehouse-base: "仓库"
aai-warehouse-logistic: "物流仓"
aai-warehouse-storage: "存货仓"
advanced-electronics-2: "高等电学 2"
advanced-electronics: "高等电学"
advanced-material-processing-2: "高等冶炼技术 2"
advanced-material-processing: "高等冶炼技术"
advanced-oil-processing: "高等原油处理"
area-mining-drill: "大型采矿机"
artillery-shell-range-1: "重炮炮弹射程 1"
artillery-shell-range-2: "重炮炮弹射程 2"
artillery-shell-range-3: "重炮炮弹射程 3"
artillery-shell-range-4: "重炮炮弹射程 4"
artillery-shell-range-5: "重炮炮弹射程 5"
artillery-shell-range-6: "重炮炮弹射程"
artillery-shell-speed-1: "重炮炮弹射速 1"
artillery-shell-speed-2: "重炮炮弹射速 2"
artillery-shell-speed-3: "重炮炮弹射速 3"
artillery-shell-speed-4: "重炮炮弹射速 4"
artillery-shell-speed-5: "重炮炮弹射速 5"
artillery-shell-speed-6: "重炮炮弹射速"
artillery: "重型火炮"
atomic-bomb: "原子弹"
automated-rail-transportation: "铁路自动运输系统"
automation-2: "自动化 2"
automation-3: "自动化 3"
automation: "自动化"
automobilism: "汽车"
basic-fluid-handling: "基础流体处理"
basic-logistics: "基础物流"
battery-equipment: "电池组模块"
battery-mk2-equipment: "电池组模块MK2"
battery: "电池"
belt-immunity-equipment: "锚定模块"
braking-force-1: "制动技术 1"
braking-force-2: "制动技术 2"
braking-force-3: "制动技术 3"
braking-force-4: "制动技术 4"
braking-force-5: "制动技术 5"
braking-force-6: "制动技术 6"
braking-force-7: "制动技术 7"
chemical-science-pack: "化工研究包 (蓝瓶)"
circuit-network: "信号网络"
cliff-explosives: "悬崖炸药"
coal-liquefaction: "煤炭液化"
concrete-walls: "混凝土墙"
concrete: "混凝土"
construction-robotics: "建设机器人"
defender: "防御无人机"
destroyer: "进攻无人机"
discharge-defense-equipment: "放电防御模块"
distractor: "掩护无人机"
effect-transmission: "插件效果分享"
effectivity-module-2: "节能插件 2"
effectivity-module-3: "节能插件 3"
effectivity-module-4: "节能插件 4"
effectivity-module-5: "节能插件 5"
effectivity-module-6: "节能插件 6"
effectivity-module-7: "节能插件 7"
effectivity-module-8: "节能插件 8"
effectivity-module-9: "节能插件 9"
effectivity-module: "节能插件"
electric-energy-accumulators: "电能储存"
electric-energy-distribution-1: "电能传输 1"
electric-energy-distribution-2: "电能传输 2"
electric-engine: "大型电动机"
electric-lab: "电力研究中心"
electric-mining: "电力采矿机"
electricity: "电力"
electronics: "基础电学"
energy-shield-equipment: "能量护盾"
energy-shield-mk2-equipment: "能量护盾 MK2"
energy-shield-mk3-equipment: "能量护盾 MK3"
energy-shield-mk4-equipment: "能量护盾 MK4"
energy-shield-mk5-equipment: "能量护盾 MK5"
energy-shield-mk6-equipment: "能量护盾 MK6"
energy-weapons-damage-10: "能量武器伤害"
energy-weapons-damage-1: "能量武器伤害 1"
energy-weapons-damage-2: "能量武器伤害 2"
energy-weapons-damage-3: "能量武器伤害 3"
energy-weapons-damage-4: "能量武器伤害 4"
energy-weapons-damage-5: "能量武器伤害 5"
energy-weapons-damage-6: "能量武器伤害 6"
energy-weapons-damage-7: "能量武器伤害 7"
energy-weapons-damage-8: "能量武器伤害 8"
energy-weapons-damage-9: "能量武器伤害 9"
engine: "多缸发动机"
equipment-gantry: "Equipment gantry"
exoskeleton-equipment: "外骨骼模块"
explosive-rocketry: "爆破火箭弹"
explosives: "炸药"
factory-architecture-t1: "工厂建筑学 1"
factory-architecture-t2: "工厂建筑学 2"
factory-architecture-t3: "工厂建筑学 3"
factory-connection-type-chest: "工厂升级: 箱子连接"
factory-connection-type-circuit: "工厂升级: 信号网络连接"
factory-connection-type-fluid: "工厂升级: 流体连接"
factory-interior-upgrade-display: "工厂升级: ALT视图显示"
factory-interior-upgrade-lights: "工厂升级: 室内照明"
factory-preview: "工厂升级: 预览"
factory-recursion-t1: "工厂嵌套学 1"
factory-recursion-t2: "工厂嵌套学 2"
factory-requester-chest: "工厂集货箱"
fast-inserter: "高速机械臂"
filter-inserter: "筛选机械臂"
flamethrower: "火焰喷射"
flammables: "燃料制备"
fluid-handling: "流体操作"
fluid-wagon: "液罐车厢"
follower-robot-count-10: "无人机跟随数量"
follower-robot-count-1: "无人机跟随数量 1"
follower-robot-count-2: "无人机跟随数量 2"
follower-robot-count-3: "无人机跟随数量 3"
follower-robot-count-4: "无人机跟随数量 4"
follower-robot-count-5: "无人机跟随数量 5"
follower-robot-count-6: "无人机跟随数量 6"
follower-robot-count-7: "无人机跟随数量 7"
follower-robot-count-8: "无人机跟随数量 8"
follower-robot-count-9: "无人机跟随数量 9"
fuel-processing: "燃料加工"
fusion-reactor-equipment: "聚变堆模块"
gate: "闸门"
glass-processing: "玻璃处理"
grappling-gun: "抓钩枪"
gun-turret: "机枪炮塔"
heavy-armor: "重型护甲"
industrial-furnace: "工业熔炉"
inserter-capacity-bonus-1: "机械臂搬运量加成 1"
inserter-capacity-bonus-2: "机械臂搬运量加成 2"
inserter-capacity-bonus-3: "机械臂搬运量加成 3"
inserter-capacity-bonus-4: "机械臂搬运量加成 4"
inserter-capacity-bonus-5: "机械臂搬运量加成 5"
inserter-capacity-bonus-6: "机械臂搬运量加成 6"
inserter-capacity-bonus-7: "机械臂搬运量加成 7"
jetpack-1: "喷气背包模块 1"
jetpack-2: "喷气背包模块 2"
jetpack-3: "喷气背包模块 3"
jetpack-4: "喷气背包模块 4"
kovarex-enrichment-process: "铀增殖处理"
land-mine: "地雷"
landfill: "填海料"
laser-shooting-speed-1: "激光射速 1"
laser-shooting-speed-2: "激光射速 2"
laser-shooting-speed-3: "激光射速 3"
laser-shooting-speed-4: "激光射速 4"
laser-shooting-speed-5: "激光射速 5"
laser-shooting-speed-6: "激光射速 6"
laser-shooting-speed-7: "激光射速 7"
laser-turret: "激光炮塔"
laser: "激光"
logistic-robotics: "物流机器人"
logistic-science-pack: "物流研究包 (绿瓶)"
logistic-system: "物流系统"
logistic-train-network: "物流火车网"
logistics-2: "物流学 2"
logistics-3: "物流学 3"
logistics: "物流学"
long-inserters-1: "Long inserters 1"
long-inserters-2: "Long inserters 2"
low-density-structure: "轻质框架"
lubricant: "润滑油"
medium-electric-pole: "中型电线杆"
military-2: "军工学 2"
military-3: "军工学 3"
military-4: "军工学 4"
military-science-pack: "军备研究包 (灰瓶)"
military: "军工学"
mining-productivity-10: "采矿产能 10"
mining-productivity-11: "采矿产能 11"
mining-productivity-12: "采矿产能 12"
mining-productivity-13: "采矿产能"
mining-productivity-1: "采矿产能 1"
mining-productivity-2: "采矿产能 2"
mining-productivity-3: "采矿产能 3"
mining-productivity-4: "采矿产能 4"
mining-productivity-5: "采矿产能 5"
mining-productivity-6: "采矿产能 6"
mining-productivity-7: "采矿产能 7"
mining-productivity-8: "采矿产能 8"
mining-productivity-9: "采矿产能 9"
modular-armor: "模块装甲"
modules: "插件"
more-inserters-1: "More inserters 1"
more-inserters-2: "More inserters 2"
near-inserters: "Near inserters"
night-vision-equipment: "夜视模块"
nuclear-fuel-reprocessing: "乏燃料后处理"
nuclear-power: "核能"
oil-processing: "基础原油处理"
optics: "基础光学"
personal-laser-defense-equipment: "激光防御模块"
personal-roboport-equipment: "机器人指令模块"
personal-roboport-mk2-equipment: "机器人指令模块MK2"
physical-projectile-damage-10: "动能武器伤害"
physical-projectile-damage-1: "动能武器伤害 1"
physical-projectile-damage-2: "动能武器伤害 2"
physical-projectile-damage-3: "动能武器伤害 3"
physical-projectile-damage-4: "动能武器伤害 4"
physical-projectile-damage-5: "动能武器伤害 5"
physical-projectile-damage-6: "动能武器伤害 6"
physical-projectile-damage-7: "动能武器伤害 7"
physical-projectile-damage-8: "动能武器伤害 8"
physical-projectile-damage-9: "动能武器伤害 9"
plastics: "塑料"
power-armor-mk2: "能量装甲MK2"
power-armor: "能量装甲"
production-science-pack: "生产研究包 (紫瓶)"
productivity-module-2: "产能插件 2"
productivity-module-3: "产能插件 3"
productivity-module-4: "产能插件 4"
productivity-module-5: "产能插件 5"
productivity-module-6: "产能插件 6"
productivity-module-7: "产能插件 7"
productivity-module-8: "产能插件 8"
productivity-module-9: "产能插件 9"
productivity-module: "产能插件"
radar: "雷达"
rail-signals: "铁路信号"
railway: "铁路"
refined-flammables-10: "精炼燃料制备"
refined-flammables-1: "精炼燃料制备 1"
refined-flammables-2: "精炼燃料制备 2"
refined-flammables-3: "精炼燃料制备 3"
refined-flammables-4: "精炼燃料制备 4"
refined-flammables-5: "精炼燃料制备 5"
refined-flammables-6: "精炼燃料制备 6"
refined-flammables-7: "精炼燃料制备 7"
refined-flammables-8: "精炼燃料制备 8"
refined-flammables-9: "精炼燃料制备 9"
research-speed-1: "研究中心研发速度 1"
research-speed-2: "研究中心研发速度 2"
research-speed-3: "研究中心研发速度 3"
research-speed-4: "研究中心研发速度 4"
research-speed-5: "研究中心研发速度 5"
research-speed-6: "研究中心研发速度 6"
robot-attrition-explosion-safety: "Swarm safety"
robotics: "机器人技术"
rocket-control-unit: "火箭控制器"
rocket-fuel: "火箭燃料"
rocket-silo: "卫星火箭发射井"
rocketry: "军用火箭学"
sand-processing: "沙处理"
se-adaptive-armour-1: "自适应装甲 1"
se-adaptive-armour-2: "自适应装甲 2"
se-adaptive-armour-3: "自适应装甲 3"
se-adaptive-armour-4: "自适应装甲 4"
se-adaptive-armour-5: "自适应装甲 5"
se-addon-power-pole: "附加式电线杆"
se-aeroframe-bulkhead: "航空框架隔板"
se-aeroframe-pole: "航空框架杆"
se-aeroframe-scaffold: "航空框架支架"
se-antimatter-engine: "反物质引擎"
se-antimatter-production: "反物质生产"
se-antimatter-reactor: "反物质反应堆"
se-arcosphere-folding: "曲虹球折叠"
se-arcosphere: "曲虹球收集"
se-astronomic-science-pack-1: "天文学研究包 1"
se-astronomic-science-pack-2: "天文学研究包 2"
se-astronomic-science-pack-3: "天文学研究包 3"
se-astronomic-science-pack-4: "天文学研究包 4"
se-big-heat-exchanger: "高温换热器"
se-big-turbine: "高温冷凝汽轮机"
se-bio-upgrade-agility-1: "生化升级：敏捷 1"
se-bio-upgrade-agility-2: "生化升级：敏捷 2"
se-bio-upgrade-agility-3: "生化升级：敏捷 3"
se-bio-upgrade-agility-4: "生化升级：敏捷 4"
se-bio-upgrade-agility-5: "生化升级：敏捷 5"
se-bio-upgrade-constitution-1: "生化升级：体质 1"
se-bio-upgrade-constitution-2: "生化升级：体质 2"
se-bio-upgrade-constitution-3: "生化升级：体质 3"
se-bio-upgrade-constitution-4: "生化升级：体质 4"
se-bio-upgrade-constitution-5: "生化升级：体质 5"
se-bio-upgrade-dexterity-1: "生化升级：灵巧 1"
se-bio-upgrade-dexterity-2: "生化升级：灵巧 2"
se-bio-upgrade-dexterity-3: "生化升级：灵巧 3"
se-bio-upgrade-dexterity-4: "生化升级：灵巧 4"
se-bio-upgrade-dexterity-5: "生化升级：灵巧 5"
se-bio-upgrade-intelligence-1: "生化升级：智力 1"
se-bio-upgrade-intelligence-2: "生化升级：智力 2"
se-bio-upgrade-intelligence-3: "生化升级：智力 3"
se-bio-upgrade-intelligence-4: "生化升级：智力 4"
se-bio-upgrade-intelligence-5: "生化升级：智力 5"
se-bio-upgrade-strength-1: "生化升级：力量 1"
se-bio-upgrade-strength-2: "生化升级：力量 2"
se-bio-upgrade-strength-3: "生化升级：力量 3"
se-bio-upgrade-strength-4: "生化升级：力量 4"
se-bio-upgrade-strength-5: "生化升级：力量 5"
se-biogun: "生化枪"
se-biological-science-pack-1: "生物学研究包 1"
se-biological-science-pack-2: "生物学研究包 2"
se-biological-science-pack-3: "生物学研究包 3"
se-biological-science-pack-4: "生物学研究包 4"
se-bioscrubber: "生物洗涤器"
se-capsule-behemoth-biter: "生物胶囊（巨型撕咬虫）"
se-capsule-behemoth-spitter: "生物胶囊（巨型喷吐虫）"
se-capsule-big-biter: "生物胶囊（大型撕咬虫）"
se-capsule-big-spitter: "生物胶囊（大型喷吐虫）"
se-capsule-medium-biter: "生物胶囊（中型撕咬虫）"
se-capsule-medium-spitter: "生物胶囊（中型喷吐虫）"
se-capsule-small-biter: "生物胶囊（小型撕咬虫）"
se-capsule-small-spitter: "生物胶囊（小型喷吐虫）"
se-cargo-rocket-section-beryllium: "铍制运载火箭区段"
se-centrifuge: "离心机"
se-compact-beacon-2: "紧凑型插件分享塔 2"
se-compact-beacon: "紧凑型插件分享塔"
se-condenser-turbine: "冷凝涡轮技术"
se-core-miner: "星核采集技术"
se-cryogun: "冷冻枪"
se-cryonite-lubricant: "冰晶润滑剂"
se-deep-catalogue-1: "深空目录 1"
se-deep-catalogue-2: "深空目录 2"
se-deep-catalogue-3: "深空目录 3"
se-deep-catalogue-4: "深空目录 4"
se-deep-space-science-pack-1: "深空科学研究包 1"
se-deep-space-science-pack-2: "深空科学研究包 2"
se-deep-space-science-pack-3: "深空科学研究包 3"
se-deep-space-science-pack-4: "深空科学研究包 4"
se-deep-space-transport-belt: "深空传送带"
se-delivery-cannon-capsule-iridium: "铱制货运火炮货舱"
se-delivery-cannon-weapon: "武器投射火炮"
se-delivery-cannon: "货运火炮"
se-dimensional-anchor: "次元锚"
se-dynamic-emitter: "动态发射器"
se-electric-boiler: "电锅炉"
se-energy-beam-defence: "保护伞：能量束防御设施"
se-energy-beaming: "能量束"
se-energy-science-pack-1: "能量学研究包 1"
se-energy-science-pack-2: "能量学研究包 2"
se-energy-science-pack-3: "能量学研究包 3"
se-energy-science-pack-4: "能量学研究包 4"
se-factory-spaceship-1: "工厂飞船 1"
se-factory-spaceship-2: "工厂飞船 2"
se-factory-spaceship-3: "工厂飞船 3"
se-factory-spaceship-4: "工厂飞船 4"
se-factory-spaceship-5: "工厂飞船"
se-fluid-burner-generator: "燃油发电技术"
se-fuel-refining: "燃料精炼技术"
se-heat-shielding-iridium: "铱制隔热瓦"
se-heat-shielding: "隔热技术"
se-heavy-assembly: "重型机械组件"
se-heavy-bearing: "重型轴承"
se-heavy-composite: "重型复合材料"
se-heavy-girder: "重型梁架"
se-holmium-cable: "钬电缆"
se-holmium-solenoid: "钬螺线管"
se-ion-engine: "离子引擎"
se-lattice-pressure-vessel: "晶格压力容器"
se-lifesupport-equipment-1: "维生装备 1"
se-lifesupport-equipment-2: "维生装备 2"
se-lifesupport-equipment-3: "维生装备 3"
se-lifesupport-equipment-4: "维生装备 4"
se-lifesupport-facility: "维生设施"
se-linked-container: "曲连存储"
se-long-range-star-mapping: "长距离星图绘制"
se-low-density-structure-beryllium: "铍制轻质框架"
se-material-science-pack-1: "材料学研究包 1"
se-material-science-pack-2: "材料学研究包 2"
se-material-science-pack-3: "材料学研究包 3"
se-material-science-pack-4: "材料学研究包 4"
se-medpack-2: "医疗包 2"
se-medpack-3: "医疗包 3"
se-medpack-4: "医疗包 4"
se-medpack: "医疗包"
se-meteor-defence: "广域陨石防御系统"
se-meteor-point-defence: "陨石点防御系统"
se-nanomaterial: "纳米材料"
se-naquium-cube: "寂介素立方体"
se-naquium-processor: "寂介素处理器"
se-naquium-tessaract: "高维矢量超立方块"
se-nexus: "枢纽"
se-plague: "生物武器"
se-processing-beryllium: "铍处理"
se-processing-cryonite: "冰晶石处理"
se-processing-holmium: "钬处理"
se-processing-iridium: "铱处理"
se-processing-methane-ice: "甲烷冰处理"
se-processing-naquium: "寂介素处理"
se-processing-unit-holmium: "处理器高效制造"
se-processing-vitamelange: "维生质处理"
se-processing-vulcanite: "火成岩处理"
se-processing-water-ice: "水冰处理"
se-pulveriser: "粉碎机"
se-pylon-construction-radar: "建设网络式雷达输电塔"
se-pylon-construction: "建设网络式输电塔"
se-pylon-substation: "广域配电式输电塔"
se-pylon: "输电塔"
se-pyroflux-smelting-beryllium: "热熔剂冶炼铍矿"
se-pyroflux-smelting-holmium: "热熔剂冶炼钬矿"
se-pyroflux-smelting: "热熔剂冶炼"
se-quantum-processor: "量子处理器"
se-railgun: "磁轨武器"
se-recycling-facility: "回收设施"
se-rocket-cargo-safety-1: "运载火箭安全性 1"
se-rocket-cargo-safety-2: "运载火箭安全性 2"
se-rocket-cargo-safety-3: "运载火箭安全性 3"
se-rocket-cargo-safety-4: "运载火箭安全性"
se-rocket-fuel-from-water: "电解水制燃料技术"
se-rocket-landing-pad: "火箭着陆台"
se-rocket-launch-pad: "运载火箭发射井"
se-rocket-reusability-1: "可重复使用火箭 1"
se-rocket-reusability-2: "可重复使用火箭 2"
se-rocket-reusability-3: "可重复使用火箭 3"
se-rocket-reusability-4: "可重复使用火箭"
se-rocket-science-pack: "火箭研究包"
se-rocket-survivability-1: "火箭生存能力 1"
se-rocket-survivability-2: "火箭生存能力 2"
se-rocket-survivability-3: "火箭生存能力 3"
se-rocket-survivability-4: "火箭生存能力"
se-rtg-equipment-2: "便携式 RTG MK1 2"
se-rtg-equipment: "便携式 RTG MK1"
se-self-sealing-gel: "自封凝胶"
se-space-accumulator-2: "寂介素电池技术"
se-space-accumulator: "钬电池技术"
se-space-assembling: "太空组装技术"
se-space-astrometrics-laboratory: "天体测量设施"
se-space-belt: "太空物流学"
se-space-biochemical-laboratory: "生物化学设施"
se-space-capsule-navigation: "太空舱导航学"
se-space-catalogue-astronomic-1: "天文学目录 1"
se-space-catalogue-astronomic-2: "天文学目录 2"
se-space-catalogue-astronomic-3: "天文学目录 3"
se-space-catalogue-astronomic-4: "天文学目录 4"
se-space-catalogue-biological-1: "生物学目录 1"
se-space-catalogue-biological-2: "生物学目录 2"
se-space-catalogue-biological-3: "生物学目录 3"
se-space-catalogue-biological-4: "生物学目录 4"
se-space-catalogue-energy-1: "能量学目录 1"
se-space-catalogue-energy-2: "能量学目录 2"
se-space-catalogue-energy-3: "能量学目录 3"
se-space-catalogue-energy-4: "能量学目录 4"
se-space-catalogue-material-1: "材料学目录 1"
se-space-catalogue-material-2: "材料学目录 2"
se-space-catalogue-material-3: "材料学目录 3"
se-space-catalogue-material-4: "材料学目录 4"
se-space-data-card: "数据卡"
se-space-decontamination-facility: "净化设施"
se-space-electromagnetics-laboratory: "电磁学设施"
se-space-elevator-cable-nano: "纳米缆索 2"
se-space-elevator: "太空电梯"
se-space-genetics-laboratory: "遗传学设施"
se-space-gravimetrics-laboratory: "重力学设施"
se-space-growth-facility: "培养设施"
se-space-hypercooling-1: "超级冷却技术 1"
se-space-hypercooling-2: "超级冷却技术 2"
se-space-hypercooling-3: "超级冷却技术 3"
se-space-laser-laboratory: "激光设施"
se-space-manufactory: "太空制造技术"
se-space-material-fabricator: "物质合成技术"
se-space-matter-fusion: "物质聚变"
se-space-mechanical-laboratory: "空间机械加工设施"
se-space-particle-accelerator: "粒子加速器"
se-space-particle-collider: "粒子对撞器"
se-space-pipe: "太空流体处理"
se-space-plasma-generator: "等离子生成"
se-space-platform-plating: "镀层轨道平台"
se-space-platform-scaffold: "轨道平台框架"
se-space-probe: "太空探测火箭发射井"
se-space-radiating-efficiency: "散热效率"
se-space-radiating-speed: "散热速度"
se-space-radiation-laboratory: "辐射设施"
se-space-radiator-1: "散热器 1"
se-space-radiator-2: "散热器 2"
se-space-rail: "太空铁路"
se-space-science-lab: "空间科学研究"
se-space-simulation-ab: "有生源说模拟"
se-space-simulation-abm: "变异情况模拟"
se-space-simulation-am: "空间材料模拟"
se-space-simulation-as: "空间粒子模拟"
se-space-simulation-asb: "空间生物学模拟"
se-space-simulation-asbm: "宇宙学模拟"
se-space-simulation-asm: "天体物理学模拟"
se-space-simulation-bm: "生物力学模拟"
se-space-simulation-sb: "生物化学模拟"
se-space-simulation-sbm: "纳米模拟"
se-space-simulation-sm: "纳米材料模拟"
se-space-solar-panel-2: "平板太阳能板 2"
se-space-solar-panel-3: "平板太阳能板 3"
se-space-solar-panel: "平板太阳能板"
se-space-supercomputer-1: "超级计算机 1"
se-space-supercomputer-2: "超级计算机 2"
se-space-supercomputer-3: "超级计算机 3"
se-space-supercomputer-4: "超级计算机 4"
se-space-telescope-gammaray: "伽马射线望远镜"
se-space-telescope-microwave: "微波望远镜"
se-space-telescope-radio: "射电望远镜"
se-space-telescope-xray: "X射线望远镜"
se-space-telescope: "望远镜"
se-space-thermodynamics-laboratory: "热力学设施"
se-spaceship-clamps: "飞船对接夹钳"
se-spaceship-integrity-1: "飞船结构强度 1"
se-spaceship-integrity-2: "飞船结构强度 2"
se-spaceship-integrity-3: "飞船结构强度 3"
se-spaceship-integrity-4: "飞船结构强度 4"
se-spaceship-integrity-5: "飞船结构强度 5"
se-spaceship-integrity-6: "飞船结构强度 6"
se-spaceship-integrity-7: "飞船结构强度 7"
se-spaceship-victory: "飞船胜利"
se-spaceship: "飞船"
se-supercharger: "超充能器"
se-superconductive-cable: "超导技术"
se-teleportation: "传送技术"
se-tesla-gun: "特斯拉武器"
se-thruster-suit-2: "推进式太空服 2"
se-thruster-suit-3: "推进式太空服 3"
se-thruster-suit-4: "推进式太空服 4"
se-thruster-suit: "推进式太空服"
se-vitalic-acid: "维生质酸"
se-vitalic-epoxy: "维生质环氧树脂"
se-vitalic-reagent: "维生质"
se-vulcanite-rocket-fuel: "高效火箭燃料"
se-wide-beacon-2: "广域信标 2"
se-wide-beacon: "广域信标"
se-zone-discovery-deep: "深空探测"
se-zone-discovery-random: "星区探测"
se-zone-discovery-targeted: "星区定向探测"
shield-projector: "护盾投射器"
solar-energy: "太阳能"
solar-panel-equipment: "太阳能模块"
space-science-pack: "天文学研究包"
speed-module-2: "速度插件 2"
speed-module-3: "速度插件 3"
speed-module-4: "速度插件 4"
speed-module-5: "速度插件 5"
speed-module-6: "速度插件 6"
speed-module-7: "速度插件 7"
speed-module-8: "速度插件 8"
speed-module-9: "速度插件 9"
speed-module: "速度插件"
spidertron: "蜘蛛机甲"
stack-filter-inserter: "集装筛选机械臂"
stack-inserter: "集装机械臂"
steam-power: "蒸汽动力"
steam-turbine: "汽轮机"
steel-axe: "钢斧镐"
steel-processing: "炼钢技术"
steel-walls: "钢刺墙"
stone-wall: "石墙"
stronger-explosives-10: "烈性炸药"
stronger-explosives-1: "烈性炸药 1"
stronger-explosives-2: "烈性炸药 2"
stronger-explosives-3: "烈性炸药 3"
stronger-explosives-4: "烈性炸药 4"
stronger-explosives-5: "烈性炸药 5"
stronger-explosives-6: "烈性炸药 6"
stronger-explosives-7: "烈性炸药 7"
stronger-explosives-8: "烈性炸药 8"
stronger-explosives-9: "烈性炸药 9"
sulfur-processing: "硫磺"
tank: "坦克"
toolbelt-2: "工具腰带 2"
toolbelt-3: "工具腰带 3"
toolbelt-4: "工具腰带 4"
toolbelt-5: "工具腰带 5"
toolbelt-6: "工具腰带 6"
toolbelt: "工具腰带"
uranium-ammo: "贫铀弹"
uranium-processing: "铀浓缩处理"
utility-science-pack: "效能研究包 (黄瓶)"
weapon-shooting-speed-1: "动能武器射速 1"
weapon-shooting-speed-2: "动能武器射速 2"
weapon-shooting-speed-3: "动能武器射速 3"
weapon-shooting-speed-4: "动能武器射速 4"
weapon-shooting-speed-5: "动能武器射速 5"
weapon-shooting-speed-6: "动能武器射速 6"
worker-robots-speed-10: "作业机器人移动速度"
worker-robots-speed-1: "作业机器人移动速度 1"
worker-robots-speed-2: "作业机器人移动速度 2"
worker-robots-speed-3: "作业机器人移动速度 3"
worker-robots-speed-4: "作业机器人移动速度 4"
worker-robots-speed-5: "作业机器人移动速度 5"
worker-robots-speed-6: "作业机器人移动速度 6"
worker-robots-speed-7: "作业机器人移动速度 7"
worker-robots-speed-8: "作业机器人移动速度 8"
worker-robots-speed-9: "作业机器人移动速度 9"
worker-robots-storage-1: "作业机器人货物运量 1"
worker-robots-storage-2: "作业机器人货物运量 2"
worker-robots-storage-3: "作业机器人货物运量 3"